//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.25 at 10:05:09 AM CET 
//


package de.foellix.aql.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}androidPlatforms"/&gt;
 *         &lt;element ref="{}androidBuildTools"/&gt;
 *         &lt;element ref="{}maxMemory"/&gt;
 *         &lt;element ref="{}tools"/&gt;
 *         &lt;element ref="{}preprocessors"/&gt;
 *         &lt;element ref="{}operators"/&gt;
 *         &lt;element ref="{}converters"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "androidPlatforms",
    "androidBuildTools",
    "maxMemory",
    "tools",
    "preprocessors",
    "operators",
    "converters"
})
@XmlRootElement(name = "config")
public class Config {

    @XmlElement(required = true)
    protected String androidPlatforms;
    @XmlElement(required = true)
    protected String androidBuildTools;
    protected int maxMemory;
    @XmlElement(required = true)
    protected Tools tools;
    @XmlElement(required = true)
    protected Preprocessors preprocessors;
    @XmlElement(required = true)
    protected Operators operators;
    @XmlElement(required = true)
    protected Converters converters;

    /**
     * Gets the value of the androidPlatforms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAndroidPlatforms() {
        return androidPlatforms;
    }

    /**
     * Sets the value of the androidPlatforms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAndroidPlatforms(String value) {
        this.androidPlatforms = value;
    }

    /**
     * Gets the value of the androidBuildTools property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAndroidBuildTools() {
        return androidBuildTools;
    }

    /**
     * Sets the value of the androidBuildTools property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAndroidBuildTools(String value) {
        this.androidBuildTools = value;
    }

    /**
     * Gets the value of the maxMemory property.
     * 
     */
    public int getMaxMemory() {
        return maxMemory;
    }

    /**
     * Sets the value of the maxMemory property.
     * 
     */
    public void setMaxMemory(int value) {
        this.maxMemory = value;
    }

    /**
     * Gets the value of the tools property.
     * 
     * @return
     *     possible object is
     *     {@link Tools }
     *     
     */
    public Tools getTools() {
        return tools;
    }

    /**
     * Sets the value of the tools property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tools }
     *     
     */
    public void setTools(Tools value) {
        this.tools = value;
    }

    /**
     * Gets the value of the preprocessors property.
     * 
     * @return
     *     possible object is
     *     {@link Preprocessors }
     *     
     */
    public Preprocessors getPreprocessors() {
        return preprocessors;
    }

    /**
     * Sets the value of the preprocessors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Preprocessors }
     *     
     */
    public void setPreprocessors(Preprocessors value) {
        this.preprocessors = value;
    }

    /**
     * Gets the value of the operators property.
     * 
     * @return
     *     possible object is
     *     {@link Operators }
     *     
     */
    public Operators getOperators() {
        return operators;
    }

    /**
     * Sets the value of the operators property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operators }
     *     
     */
    public void setOperators(Operators value) {
        this.operators = value;
    }

    /**
     * Gets the value of the converters property.
     * 
     * @return
     *     possible object is
     *     {@link Converters }
     *     
     */
    public Converters getConverters() {
        return converters;
    }

    /**
     * Sets the value of the converters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Converters }
     *     
     */
    public void setConverters(Converters value) {
        this.converters = value;
    }

}
