//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.25 at 10:05:09 AM CET 
//


package de.foellix.aql.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}priority" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}timeout" minOccurs="0"/&gt;
 *         &lt;element ref="{}execute"/&gt;
 *         &lt;element ref="{}path" minOccurs="0"/&gt;
 *         &lt;element ref="{}runOnEntry" minOccurs="0"/&gt;
 *         &lt;element ref="{}runOnExit" minOccurs="0"/&gt;
 *         &lt;element ref="{}runOnSuccess" minOccurs="0"/&gt;
 *         &lt;element ref="{}runOnFail" minOccurs="0"/&gt;
 *         &lt;element ref="{}runOnAbort" minOccurs="0"/&gt;
 *         &lt;element ref="{}questions"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="external" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "priority",
    "timeout",
    "execute",
    "path",
    "runOnEntry",
    "runOnExit",
    "runOnSuccess",
    "runOnFail",
    "runOnAbort",
    "questions"
})
@XmlRootElement(name = "tool")
public class Tool {

    protected List<Priority> priority;
    protected String timeout;
    @XmlElement(required = true)
    protected Execute execute;
    protected String path;
    protected String runOnEntry;
    protected String runOnExit;
    protected String runOnSuccess;
    protected String runOnFail;
    protected String runOnAbort;
    @XmlElement(required = true)
    protected String questions;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "external")
    protected Boolean external;

    /**
     * Gets the value of the priority property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priority property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriority().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Priority }
     * 
     * 
     */
    public List<Priority> getPriority() {
        if (priority == null) {
            priority = new ArrayList<Priority>();
        }
        return this.priority;
    }

    /**
     * Gets the value of the timeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeout(String value) {
        this.timeout = value;
    }

    /**
     * Gets the value of the execute property.
     * 
     * @return
     *     possible object is
     *     {@link Execute }
     *     
     */
    public Execute getExecute() {
        return execute;
    }

    /**
     * Sets the value of the execute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Execute }
     *     
     */
    public void setExecute(Execute value) {
        this.execute = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the runOnEntry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunOnEntry() {
        return runOnEntry;
    }

    /**
     * Sets the value of the runOnEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunOnEntry(String value) {
        this.runOnEntry = value;
    }

    /**
     * Gets the value of the runOnExit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunOnExit() {
        return runOnExit;
    }

    /**
     * Sets the value of the runOnExit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunOnExit(String value) {
        this.runOnExit = value;
    }

    /**
     * Gets the value of the runOnSuccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunOnSuccess() {
        return runOnSuccess;
    }

    /**
     * Sets the value of the runOnSuccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunOnSuccess(String value) {
        this.runOnSuccess = value;
    }

    /**
     * Gets the value of the runOnFail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunOnFail() {
        return runOnFail;
    }

    /**
     * Sets the value of the runOnFail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunOnFail(String value) {
        this.runOnFail = value;
    }

    /**
     * Gets the value of the runOnAbort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunOnAbort() {
        return runOnAbort;
    }

    /**
     * Sets the value of the runOnAbort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunOnAbort(String value) {
        this.runOnAbort = value;
    }

    /**
     * Gets the value of the questions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestions() {
        return questions;
    }

    /**
     * Sets the value of the questions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestions(String value) {
        this.questions = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the external property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isExternal() {
        if (external == null) {
            return false;
        } else {
            return external;
        }
    }

    /**
     * Sets the value of the external property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExternal(Boolean value) {
        this.external = value;
    }

}
