//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.25 at 10:05:09 AM CET 
//


package de.foellix.aql.datastructure;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}permissions"/&gt;
 *         &lt;element ref="{}intentsources"/&gt;
 *         &lt;element ref="{}intentsinks"/&gt;
 *         &lt;element ref="{}intents"/&gt;
 *         &lt;element ref="{}intentfilters"/&gt;
 *         &lt;element ref="{}flows"/&gt;
 *         &lt;element ref="{}sources"/&gt;
 *         &lt;element ref="{}sinks"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "permissions",
    "intentsources",
    "intentsinks",
    "intents",
    "intentfilters",
    "flows",
    "sources",
    "sinks"
})
@XmlRootElement(name = "answer")
public class Answer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected Permissions permissions;
    @XmlElement(required = true)
    protected Intentsources intentsources;
    @XmlElement(required = true)
    protected Intentsinks intentsinks;
    @XmlElement(required = true)
    protected Intents intents;
    @XmlElement(required = true)
    protected Intentfilters intentfilters;
    @XmlElement(required = true)
    protected Flows flows;
    @XmlElement(required = true)
    protected Sources sources;
    @XmlElement(required = true)
    protected Sinks sinks;

    /**
     * Gets the value of the permissions property.
     * 
     * @return
     *     possible object is
     *     {@link Permissions }
     *     
     */
    public Permissions getPermissions() {
        return permissions;
    }

    /**
     * Sets the value of the permissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Permissions }
     *     
     */
    public void setPermissions(Permissions value) {
        this.permissions = value;
    }

    /**
     * Gets the value of the intentsources property.
     * 
     * @return
     *     possible object is
     *     {@link Intentsources }
     *     
     */
    public Intentsources getIntentsources() {
        return intentsources;
    }

    /**
     * Sets the value of the intentsources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Intentsources }
     *     
     */
    public void setIntentsources(Intentsources value) {
        this.intentsources = value;
    }

    /**
     * Gets the value of the intentsinks property.
     * 
     * @return
     *     possible object is
     *     {@link Intentsinks }
     *     
     */
    public Intentsinks getIntentsinks() {
        return intentsinks;
    }

    /**
     * Sets the value of the intentsinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Intentsinks }
     *     
     */
    public void setIntentsinks(Intentsinks value) {
        this.intentsinks = value;
    }

    /**
     * Gets the value of the intents property.
     * 
     * @return
     *     possible object is
     *     {@link Intents }
     *     
     */
    public Intents getIntents() {
        return intents;
    }

    /**
     * Sets the value of the intents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Intents }
     *     
     */
    public void setIntents(Intents value) {
        this.intents = value;
    }

    /**
     * Gets the value of the intentfilters property.
     * 
     * @return
     *     possible object is
     *     {@link Intentfilters }
     *     
     */
    public Intentfilters getIntentfilters() {
        return intentfilters;
    }

    /**
     * Sets the value of the intentfilters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Intentfilters }
     *     
     */
    public void setIntentfilters(Intentfilters value) {
        this.intentfilters = value;
    }

    /**
     * Gets the value of the flows property.
     * 
     * @return
     *     possible object is
     *     {@link Flows }
     *     
     */
    public Flows getFlows() {
        return flows;
    }

    /**
     * Sets the value of the flows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flows }
     *     
     */
    public void setFlows(Flows value) {
        this.flows = value;
    }

    /**
     * Gets the value of the sources property.
     * 
     * @return
     *     possible object is
     *     {@link Sources }
     *     
     */
    public Sources getSources() {
        return sources;
    }

    /**
     * Sets the value of the sources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sources }
     *     
     */
    public void setSources(Sources value) {
        this.sources = value;
    }

    /**
     * Gets the value of the sinks property.
     * 
     * @return
     *     possible object is
     *     {@link Sinks }
     *     
     */
    public Sinks getSinks() {
        return sinks;
    }

    /**
     * Sets the value of the sinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sinks }
     *     
     */
    public void setSinks(Sinks value) {
        this.sinks = value;
    }

}
