//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.25 at 10:05:09 AM CET 
//


package de.foellix.aql.datastructure;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}type" minOccurs="0"/&gt;
 *         &lt;element ref="{}scheme" minOccurs="0"/&gt;
 *         &lt;element ref="{}ssp" minOccurs="0"/&gt;
 *         &lt;element ref="{}sspPattern" minOccurs="0"/&gt;
 *         &lt;element ref="{}sspPrefix" minOccurs="0"/&gt;
 *         &lt;element ref="{}host" minOccurs="0"/&gt;
 *         &lt;element ref="{}port" minOccurs="0"/&gt;
 *         &lt;element ref="{}path" minOccurs="0"/&gt;
 *         &lt;element ref="{}pathPattern" minOccurs="0"/&gt;
 *         &lt;element ref="{}pathPrefix" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "scheme",
    "ssp",
    "sspPattern",
    "sspPrefix",
    "host",
    "port",
    "path",
    "pathPattern",
    "pathPrefix"
})
@XmlRootElement(name = "data")
public class Data
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String type;
    protected String scheme;
    protected String ssp;
    protected String sspPattern;
    protected String sspPrefix;
    protected String host;
    protected String port;
    protected String path;
    protected String pathPattern;
    protected String pathPrefix;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the scheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheme() {
        return scheme;
    }

    /**
     * Sets the value of the scheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheme(String value) {
        this.scheme = value;
    }

    /**
     * Gets the value of the ssp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsp() {
        return ssp;
    }

    /**
     * Sets the value of the ssp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsp(String value) {
        this.ssp = value;
    }

    /**
     * Gets the value of the sspPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSspPattern() {
        return sspPattern;
    }

    /**
     * Sets the value of the sspPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSspPattern(String value) {
        this.sspPattern = value;
    }

    /**
     * Gets the value of the sspPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSspPrefix() {
        return sspPrefix;
    }

    /**
     * Sets the value of the sspPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSspPrefix(String value) {
        this.sspPrefix = value;
    }

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost(String value) {
        this.host = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPort(String value) {
        this.port = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the pathPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathPattern() {
        return pathPattern;
    }

    /**
     * Sets the value of the pathPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathPattern(String value) {
        this.pathPattern = value;
    }

    /**
     * Gets the value of the pathPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathPrefix() {
        return pathPrefix;
    }

    /**
     * Sets the value of the pathPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathPrefix(String value) {
        this.pathPrefix = value;
    }

}
