/* Generated By:JavaCC: Do not edit this line. QuestionParserConstants.java */
package de.foellix.aql.datastructure.handler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QuestionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPERATOR1 = 5;
  /** RegularExpression Id. */
  int OPERATOR2 = 6;
  /** RegularExpression Id. */
  int SOIS1 = 7;
  /** RegularExpression Id. */
  int SOIS2 = 8;
  /** RegularExpression Id. */
  int STRING = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"FILTER\"",
    "<OPERATOR2>",
    "\"Flows\"",
    "<SOIS2>",
    "<STRING>",
    "\"?\"",
    "\"!\"",
    "\"FEATURING\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\"=\"",
    "\"FROM\"",
    "\"TO\"",
    "\"IN\"",
    "\"Statement\"",
    "\"(\"",
    "\")\"",
    "\"->\"",
    "\"Method\"",
    "\"Class\"",
    "\"App\"",
  };

}
