/* Generated By:JavaCC: Do not edit this line. QuestionParserConstants.java */
package de.foellix.aql.datastructure.handler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QuestionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IN = 5;
  /** RegularExpression Id. */
  int FROM = 6;
  /** RegularExpression Id. */
  int TO = 7;
  /** RegularExpression Id. */
  int FEATURING = 8;
  /** RegularExpression Id. */
  int USES = 9;
  /** RegularExpression Id. */
  int OPERATOR1 = 10;
  /** RegularExpression Id. */
  int OPERATOR2 = 11;
  /** RegularExpression Id. */
  int OPERATOR3 = 12;
  /** RegularExpression Id. */
  int SOIS1 = 13;
  /** RegularExpression Id. */
  int SOIS2 = 14;
  /** RegularExpression Id. */
  int STRING = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"IN\"",
    "\"FROM\"",
    "\"TO\"",
    "\"FEATURING\"",
    "\"USES\"",
    "\"FILTER\"",
    "<OPERATOR2>",
    "<OPERATOR3>",
    "\"Flows\"",
    "<SOIS2>",
    "<STRING>",
    "\"?\"",
    "\"!\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\"=\"",
    "\"Statement\"",
    "\"(\"",
    "\")\"",
    "\"->\"",
    "\"Method\"",
    "\"Class\"",
    "\"App\"",
  };

}
