/* Generated By:JavaCC: Do not edit this line. QuestionParserConstants.java */
package de.foellix.aql.datastructure.handler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QuestionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IN = 5;
  /** RegularExpression Id. */
  int FROM = 6;
  /** RegularExpression Id. */
  int TO = 7;
  /** RegularExpression Id. */
  int FEATURING = 8;
  /** RegularExpression Id. */
  int USES = 9;
  /** RegularExpression Id. */
  int WITH = 10;
  /** RegularExpression Id. */
  int FILTER_OPERATOR = 11;
  /** RegularExpression Id. */
  int OTHER_OPERATORS = 12;
  /** RegularExpression Id. */
  int CUSTOM_OPERATORS = 13;
  /** RegularExpression Id. */
  int VARIABLE = 14;
  /** RegularExpression Id. */
  int SOIS1 = 15;
  /** RegularExpression Id. */
  int SOIS2 = 16;
  /** RegularExpression Id. */
  int ENDING = 17;
  /** RegularExpression Id. */
  int STRING = 18;
  /** RegularExpression Id. */
  int INT = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"IN\"",
    "\"FROM\"",
    "\"TO\"",
    "<FEATURING>",
    "<USES>",
    "\"WITH\"",
    "\"FILTER\"",
    "<OTHER_OPERATORS>",
    "<CUSTOM_OPERATORS>",
    "<VARIABLE>",
    "<SOIS1>",
    "<SOIS2>",
    "<ENDING>",
    "<STRING>",
    "<INT>",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"$\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\"Statement\"",
    "\"(\"",
    "\")\"",
    "\"->\"",
    "\"Method\"",
    "\"Class\"",
    "\"App\"",
  };

}
